import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  sidebar: React.ReactNode;
}

export default function RootLayout({
  children,
  sidebar,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body>
        <TanStackProvider>
          <Header />
          <aside>{sidebar}</aside>
          {children}
          <Footer />
          <div id="modal-root"></div>
        </TanStackProvider>
      </body>
    </html>
  );
}
